#ifndef COMMANDS_H
#define COMMANDS_H

#define SimICPCom1 "SimICPCom1"
#define SimICPCom2 "SimICPCom2"
#define SimICPIFF "SimICPIFF"
#define SimICPLIST "SimICPLIST"
#define SimICPAA "SimICPAA"
#define SimICPAG "SimICPAG"
#define SimICPNav "SimICPNav"
#define SimICPTILS "SimICPTILS"
#define SimICPALOW "SimICPALOW"
#define SimICPTHREE "SimICPTHREE"
#define SimICPStpt "SimICPStpt"
#define SimICPCrus "SimICPCrus"
#define SimICPSIX "SimICPSIX"
#define SimICPMark "SimICPMark"
#define SimICPEIGHT "SimICPEIGHT"
#define SimICPNINE "SimICPNINE"
#define SimICPZERO "SimICPZERO"
#define SimICPCLEAR "SimICPCLEAR"
#define SimICPEnter "SimICPEnter"
#define SimICPNext "SimICPNext"
#define SimICPPrevious "SimICPPrevious"
#define SimICPDEDUP "SimICPDEDUP"
#define SimICPDEDDOWN "SimICPDEDDOWN"
#define SimICPDEDSEQ "SimICPDEDSEQ"
#define SimICPResetDED "SimICPResetDED"
#define SimDriftCO "SimDriftCO"
#define SimWarnReset "SimWarnReset"
#define SimSetWX "SimSetWX"
#define SimFlirLevelUp "SimFlirLevelUp"
#define SimFlirLevelDown "SimFlirLevelDown"
#define SimSymWheelUp "SimSymWheelUp"
#define SimSymWheelDn "SimSymWheelDn"
#define SimHUDPower "SimHUDPower"
#define SimBrtWheelUp "SimBrtWheelUp"
#define SimBrtWheelDn "SimBrtWheelDn"
#define SimRetUp "SimRetUp"
#define SimRetDn "SimRetDn"

#endif // COMMANDS_H
